aws:
  configuration:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: ${AWS_REGION}
    requiredRoleArn: ${REQUIRED_ROLE_ARN}

    ssm:
      parameters:
        mesh:
          mailboxId: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-id
          clientCert: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-cert
          clientKey: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-key
          mailboxPassword: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-password
        pdsAdaptor:
          performanceApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/pds-adaptor/performance-test
          liveTestApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/pds-adaptor/live-test
          e2eTestApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/pds-adaptor/e2e-test
        gp2gpMessenger:
          liveTestApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/gp2gp-messenger/live-test
        ehrRepository:
          liveTestApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/ehr-repo/live-test
          e2eTestApiKey: /repo/${NHS_ENVIRONMENT}/user-input/api-keys/ehr-repo/e2e-test

nhs:
  environment: ${NHS_ENVIRONMENT}
  services:
    gp2gp:
      odsCodes:
        tppPtlInt: M85019
        emisPtlInt: N82668
        repoDev: B85002
        repoTest: B86041

spring:
  main:
    web-application-type: none