aws:
  configuration:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    sessionToken: ${AWS_SESSION_TOKEN}
    region: ${AWS_REGION}
    ssm:
      parameters:
        mesh:
          mailboxId: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-id
          clientCert: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-cert
          clientKey: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-client-key
          mailboxPassword: /repo/${NHS_ENVIRONMENT}/user-input/external/mesh-mailbox-password

nhs:
  environment: ${NHS_ENVIRONMENT}
