format_version: 4
common:
  test: &test
    clean_workspace: true
    timeout: 15
    resources:
      - docker
    artifacts:
      - build:
          source: build/reports/tests/
      - build:
          source: '*-status.before.json'
          destination: before-manifests
      - build:
          source: '*-status.after.json'
          destination: after-manifests
    tabs:
      TestReport: test/index.html
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks check_env_deployed_before
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks test_continuity_e2e
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks check_env_still_deployed_after
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks trigger_gocd_job

pipelines:
  test-gocd-triggers:
    group: linear-spike
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - test-trigger-logic:
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks test_gocd_trigger_functions
  continuity-service-e2e-tests.dev:
    group: linear-spike
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - docs/**/*.*
          - src/test/java/uk/nhs/prm/deduction/e2e/performance/**/*
          - src/test/java/uk/nhs/prm/deduction/e2e/live_technical_test/**/*
          - gocd/performance.pipeline.gocd.yml
      mesh-forwarder:
        pipeline: mesh-forwarder
        stage: deploy.dev
      nems-event-processor:
        pipeline: nems-event-processor
        stage: deploy.dev
      pds-adaptor:
        pipeline: pds-adaptor
        stage: deploy.dev
      suspension-service:
        pipeline: suspension-service
        stage: deploy.dev
      re-registration-service:
        pipeline: re-registration-service
        stage: deploy.dev
    environment_variables:
      ENVIRONMENT_ID: dev
      NHS_ENVIRONMENT: dev
      UPDATE_MOF_TO_REPO: true
      FORCE_TEST_RUN: false
    stages:
      test: *test
  continuity-service-e2e-tests.test:
    group: linear-spike
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - docs/**/*.*
          - src/test/java/uk/nhs/prm/deduction/e2e/performance/**/*
          - src/test/java/uk/nhs/prm/deduction/e2e/live_technical_test/**/*
          - gocd/performance.pipeline.gocd.yml
      mesh-forwarder:
        pipeline: mesh-forwarder
        stage: deploy.test
      nems-event-processor:
        pipeline: nems-event-processor
        stage: deploy.test
      pds-adaptor:
        pipeline: pds-adaptor
        stage: deploy.test
      suspension-service:
        pipeline: suspension-service
        stage: deploy.test
      re-registration-service:
        pipeline: re-registration-service
        stage: deploy.test
    environment_variables:
      ENVIRONMENT_ID: test
      NHS_ENVIRONMENT: test
      UPDATE_MOF_TO_REPO: false
      FORCE_TEST_RUN: false
    stages:
      test: *test
