format_version: 4
pipelines:
  e2e-tests.dev:
    group: linear-spike
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - docs/**/*.*
          - src/test/java/uk/nhs/prm/deduction/e2e/performance/**/*
          - src/test/java/uk/nhs/prm/deduction/e2e/live_technical_test/**/*
          - gocd/performance.pipeline.gocd.yml
#      mesh-forwarder:
#        pipeline: mesh-forwarder
#        stage: deploy.dev
      nems-event-processor:
        pipeline: nems-event-processor
        stage: deploy.dev
      pds-adaptor:
        pipeline: pds-adaptor
        stage: deploy.dev
#      suspension-service:
#        pipeline: suspension-service
#        stage: deploy.dev
#      re-registration-service:
#        pipeline: re-registration-service
#        stage: deploy.dev
    environment_variables:
      NHS_ENVIRONMENT: dev
      UPDATE_MOF_TO_REPO: true
    stages:
      - test:
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks check_gocd_job
            - exec:
                command: sleep
                arguments:
                  - 30
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks trigger_gocd_job
