format_version: 4
common:
  common_stages: &common_stages
    clean_workspace: true
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks livetest_day1_test
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks livetest_day2_test
pipelines:
  live-technical-test.dev:
    group: continuity-service
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      inject_message:
        - tasks:
            - ./tasks livetest_inject
      <<: *common_stages

  live-technical-test.prod:
    group: continuity-service
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      dev:
        pipeline: live-technical-test.dev
        stage: day-2-test
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages: *common_stages
