format_version: 4
common:
  common_stages: &common_stages
    - run_day_1_live_test:
        clean_workspace: true
        artifacts:
          - build:
              source: build/reports/tests/
        tabs:
          TestReport: test/index.html
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks livetest_day1_test
    - run_day_2_live_test:
        clean_workspace: true
        artifacts:
          - build:
              source: build/reports/tests/
        tabs:
          TestReport: test/index.html
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks livetest_day2_test
pipelines:
  live-technical-test.dev:
    group: continuity-service
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - inject_message:
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks livetest_inject
      - *common_stages

  live-technical-test.prod:
    group: continuity-service
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
      dev:
        pipeline: live-technical-test.dev
        stage: run_day_2_live_test
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages: *common_stages
