format_version: 4

common:
  pipeline-template: &pipeline-template
    group: performance
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - performance:
          clean_workspace: true
          approval: manual
          jobs:
            performance_test:
              artifacts:
                - build:
                    source: build/reports/performance/
                - build:
                    source: build/reports/tests/
              tabs:
                performance: build/reports/performance/e2e-durations.png
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance

pipelines:
  e2e-perf-dev:
    <<: *pipeline-template
    environment_variables:
      NHS_ENVIRONMENT: dev
      PERFORMANCE_LOAD_SPEC: "12@0.2,30@0.5,60@1"
  e2e-perf-pre-prod:
    <<: *pipeline-template
    timer:
      spec: "0 45 14 * * ?"
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
      PERFORMANCE_LOAD_SPEC: "24@0.2,60@0.5,30@0.6,30@0.7,30@0.8,120@2"
