format_version: 4

common:
  pipeline-template: &pipeline-template
    group: performance
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - performance:
          #approval:
           # type: manual
          clean_workspace: true
          jobs:
            performance_test:
              artifacts:
                - build:
                    source: build/reports/tests/
                - build:
                    source: build/reports/performance/
              tabs:
                TestReport: test/index.html
                Throughput: graphs/repo-in-throughput.png
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_repo_in_performance

pipelines:
  repo_in_perf:
    <<: *pipeline-template
    environment_variables:
      NHS_ENVIRONMENT: perf
      NUMBER_OF_MESSAGES_TO_BE_PROCESSED: 2000
      INTERVAL_BETWEEN_MESSAGES_SENT_TO_MQ: 100

  repo_in_perf_evening:
    <<: *pipeline-template
    timer:
      spec: "0 30 15 * * ?"
        only_on_changes: no
    environment_variables:
      NHS_ENVIRONMENT: perf
      NUMBER_OF_MESSAGES_TO_BE_PROCESSED: 100
      INTERVAL_BETWEEN_MESSAGES_SENT_TO_MQ: 300