format_version: 4
pipelines:
  'prm-deductions-automatic-trigger-e2e-test.dev':
    group: deductions
    label_template: '${git[:8]}'
    timer:
      spec: "0 0 9,13,17,21 * * ?"
      only_on_changes: no
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      pds-adaptor:
        pipeline: prm-deductions-pds-adaptor.dev
        stage: deploy
      nems-event-processor:
        pipeline: prm-deductions-nems-event-processor.dev
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - test:
          clean_workspace: true
          jobs:
            test_e2e:
              timeout: 15
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_e2e
  'prm-deductions-automatic-trigger-e2e-test.test':
    group: deductions
    label_template: '${git[:8]}'
    timer:
      spec: "0 0 9,13,17,21 * * ?"
      only_on_changes: no
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      pds-adaptor:
        pipeline: prm-deductions-pds-adaptor.test
        stage: deploy
      nems-event-processor:
        pipeline: prm-deductions-nems-event-processor.test
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - test:
          clean_workspace: true
          jobs:
            test_e2e:
              timeout: 15
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_e2e
